apiVersion: v1
kind: Service
metadata:
  labels:
    service: searchservice-service
  name: searchservice-service
spec:
  ports:
  - name: "8088"
    port: 80
    targetPort: 8088
    protocol: TCP
  selector:
    service: searchservice
  type: LoadBalancer